export const APP = {
    SAFE_AREA_DIMENSIONS: 'SAFE_AREA_DIMENSIONS',
    SET_UNREVIEWED_ORDER: 'SET_UNREVIEWED_ORDER',
    CLOSE_REVIEW_MODAL: 'CLOSE_REVIEW_MODAL',

    GET_VENDORS_REQUEST: 'GET_VENDORS_REQUEST',
    GET_VENDORS_SUCCESS: 'GET_VENDORS_SUCCESS',
    GET_VENDORS_ERROR: 'GET_VENDORS_ERROR',
    UPDATE_VENDORS: 'UPDATE_VENDORS',

    GET_FEATURE_BLOCKS_REQUEST: 'GET_FEATURE_BLOCKS_REQUEST',
    GET_FEATURE_BLOCKS_SUCCESS: 'GET_FEATURE_BLOCKS_SUCCESS',
    GET_FEATURE_BLOCKS_ERROR: 'GET_FEATURE_BLOCKS_ERROR',

    GET_ADDRESSES_REQUEST: 'GET_ADDRESSES_REQUEST',
    GET_ADDRESSES_SUCCESS: 'GET_ADDRESSES_SUCCESS',
    GET_ADDRESSES_ERROR: 'GET_ADDRESSES_ERROR',
    UPDATE_ADDRESSES: 'UPDATE_ADDRESSES',

    DELETE_ADDRESSES_REQUEST: 'DELETE_ADDRESSES_REQUEST',
    DELETE_ADDRESSES_SUCCESS: 'DELETE_ADDRESSES_SUCCESS',
    DELETE_ADDRESSES_ERROR: 'DELETE_ADDRESSES_ERROR',

    GET_FAVOURITES_REQUEST: 'GET_FAVOURITES_REQUEST',
    GET_FAVOURITES_SUCCESS: 'GET_FAVOURITES_SUCCESS',
    GET_FAVOURITES_ERROR: 'GET_FAVOURITES_ERROR',

    CHANGE_FAVORITE_REQUEST: 'CHANGE_FAVORITE_REQUEST',
    CHANGE_FAVORITE_SUCCESS: 'CHANGE_FAVORITE_SUCCESS',
    CHANGE_FAVORITE_ERROR: 'CHANGE_FAVORITE_ERROR',

    SORT_VENDORS_BY_NAME: 'SORT_VENDORS_BY_NAME',
    SORT_VENDORS_BY_POPULARITY: 'SORT_VENDORS_BY_POPULARITY',
    SORT_VENDORS_BY_LOCATION: 'SORT_VENDORS_BY_LOCATION',
    APPLY_LOCATION: 'APPLY_LOCATION',
    APPLY_LOCATION_GEO: 'APPLY_LOCATION_GEO',
    CHECK_LOCATION: 'CHECK_LOCATION',
    RESET_BACK_TO_PARAM: 'RESET_BACK_TO_PARAM',
    FILL_CLOSED_MODAL_DATA: 'FILL_CLOSED_MODAL_DATA',
    RESET_CLOSED_MODAL_DATA: 'RESET_CLOSED_MODAL_DATA',

    GET_LAST_UNREVIEWED_ORDER_REQUEST: 'GET_LAST_UNREVIEWED_ORDER_REQUEST',
    GET_LAST_UNREVIEWED_ORDER_SUCCESS: 'GET_LAST_UNREVIEWED_ORDER_SUCCESS',
    GET_LAST_UNREVIEWED_ORDER_ERROR: 'GET_LAST_UNREVIEWED_ORDER_ERROR',

    SET_ADDRESS: 'SET_ADDRESS',

    GET_BANNERS: 'GET_BANNERS',
    GET_BANNERS_ERROR: 'GET_BANNERS_ERROR',
    GET_BANNERS_SUCCESS: 'GET_BANNERS_SUCCESS',
    SEND_BANNER_CLICKED: 'SEND_BANNER_CLICKED',

    SET_FIRST_TIME_OPEN: 'SET_FIRST_TIME_OPEN',

    LOGGED_IN: 'APP/LOGGED_IN',
    USER_LOGGED_OUT: 'APP/USER_LOGGED_OUT',
    SET_USER_DATA: 'APP/SET_USER_DATA',
    SET_HAS_VERIFIED_PHONE: 'APP/SET_HAS_VERIFIED_PHONE',
    SET_LOCATION_DATA: 'APP/SET_LOCATION_DATA',

    //CHAT
    SEND_MESSAGE: 'SEND_MESSAGE',
    ENTER_CHAT: 'ENTER_CHAT',
    INIT_CHAT_ROOM: 'INIT_CHAT_ROOM',
    INIT_CHAT_ROOM_STARTED: 'INIT_CHAT_ROOM_STARTED',
    CHAT_ROOM_EXIST: 'CHAT_ROOM_EXIST',
    INIT_CHAT_ROOM_SUCCESS: 'INIT_CHAT_ROOM_SUCCESS',
    INIT_CHAT_ROOM_ERROR: 'INIT_CHAT_ROOM_ERROR',
    NEW_MESSAGE_ARRIVED: 'NEW_MESSAGE_ARRIVED',
    MESSAGE_IS_MODIFIED: 'MESSAGE_IS_MODIFIED',
    SET_MESSAGES_SEEN: 'SET_MESSAGES_SEEN',
    BACK_TO_CHAT: 'BACK_TO_CHAT',

    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    UPDATE_CART: 'UPDATE_CART',
    UPDATE_CART_ITEMS: 'UPDATE_CART_ITEMS',
    SET_LAST_ORDER: 'SET_LAST_ORDER',
    CUTLERY_UPDATED: 'CUTLERY_UPDATED',
    RESET_CART: 'RESET_CART',

    SET_FAVOURITES: 'SET_FAVOURITES',
    SET_ALL_FAVOURITES: 'SET_ALL_FAVOURITES',

    SET_ADDRESSES: 'SET_ADDRESSES',
    DELETED_ADDRESS: 'DELETED_ADDRESS',
    ADDED_ADDRESS: 'ADDED_ADDRESS',
};
